- name: Install apt packages
  tags: apt
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - htop
    - python3
    - python3-dev
    - python3-pip
    - python3-wheel
    - python3-venv
    - docker-compose
    - docker
    - git
    - albert
    - plank
    - make
    - gcc
    - g++
    - ripgrep
    - golang
    - wget
    - terminator
    - firefox
    - batcat
    - zathura
    - ranger
