- name: Swap CapsLock and ESC
  shell: sh -c "{{ lookup('env', 'HOME') }}/dotfiles/config/swapescape.sh"

- name: Link zshrc file in ~ dir
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link
    force: yes

- name: Remove old nvim user config 
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/lua/user"
    state: absent

- name: Link nvim dotfiles/config dir in ~/.config
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/nvim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/lua/user"
    state: link
    force: yes

- name: Link fonts dir in ~/.fonts
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/fonts"
    dest: "{{ lookup('env', 'HOME') }}/.fonts"
    state: link
    force: yes

- name: Link plank themes in ~/.local/share/plank
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/plank"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/plank"
    state: link
    force: yes

- name: Link albert configuration
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/albert/albert.conf"
    dest: "{{ lookup('env', 'HOME') }}/.config/albert.conf"
    state: link
    force: yes

- name: Copy albert themes in Arch
  become: true
  become_user: root
  copy:
    src: "{{ item }}"
    dest: /usr/share/albert/widgetsboxmodel/themes/
  with_fileglob: "{{ lookup('env', 'HOME') }}/dotfiles/config/albert/*.qss"

- name: Copy albert themes in Ubuntu
  become: true
  become_user: root
  copy:
    src: "{{ item }}"
    dest: /usr/share/albert/org.albert.frontend.widgetboxmodel/themes/
  with_fileglob: "{{ lookup('env', 'HOME') }}/dotfiles/config/albert/*.qss"

- name: Remove old autostart config
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/autostart"
    state: absent

- name: Link autostart config
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/autostart"
    dest: "{{ lookup('env', 'HOME') }}/.config/autostart"
    state: link
    force: yes

- name: Download la-capitaine icons
  git:
    force: yes
    repo: https://github.com/keeferrourke/la-capitaine-icon-theme
    dest: "{{ lookup('env', 'HOME') }}/.icons/la-capitaine-icons-theme"
    depth: 1

- name: Download WhiteSur icons
  git:
    force: yes
    repo: https://github.com/vinceliuice/WhiteSur-icon-theme
    dest: "{{ lookup('env', 'HOME') }}/bin/WhiteSur-icon-theme"
    depth: 1

- name: Install WhiteSur icons
  become: true
  become_user: root
  shell: sh "{{ lookup('env', 'HOME') }}/bin/WhiteSur-icon-theme/install.sh"

- name: Download WhiteSur-gtk-theme
  git:
    force: yes
    repo: https://github.com/vinceliuice/WhiteSur-gtk-theme
    dest: "{{ lookup('env', 'HOME') }}/bin/WhiteSur-gtk-theme"
    depth: 1

- name: Install WhiteSur-gtk-theme
  become: true
  become_user: root
  shell: sh "{{ lookup('env', 'HOME') }}/bin/WhiteSur-gtk-theme/install.sh"

# - name: Configure firefox based on WhiteSur-gtk-theme
#   become: true
#   become_user: root
#   shell: sh "{{ lookup('env', 'HOME') }}/bin/WhiteSur-gtk-theme/tweaks.sh" -f monterey

- name: Configure gdm based on WhiteSur-gtk-theme
  become: true
  become_user: root
  shell: sh "{{ lookup('env', 'HOME') }}/bin/WhiteSur-gtk-theme/tweaks.sh" -g -N -b "{{ lookup('env', 'HOME') }}/dotfiles/config/wallpapers/wallpaper-default.jpg"

- name: Download McMojave-cursors
  git:
    force: yes
    repo: https://github.com/vinceliuice/McMojave-cursors
    dest: "{{ lookup('env', 'HOME') }}/bin/McMojave-cursors"
    depth: 1

- name: Install McMojave-cursors
  become: true
  become_user: root
  shell: sh "{{ lookup('env', 'HOME') }}/bin/McMojave-cursors/install.sh"

- name: Link tmux config
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link
    force: yes

- name: Install TPM for tmux
  git:
    force: yes
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    depth: 1

- name: Link alacritty config
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/alacritty.toml"
    dest: "{{ lookup('env', 'HOME') }}/.config/alacritty/alacritty.toml"
    state: link
    force: yes
