- name: Links zshrc file in ~ dir
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link
    force: yes

- name: Links nvim dotfiles/config dir in ~/.config
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/nvim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/lua/user"
    state: link
    force: yes

- name: Links fonts dir in ~/.fonts
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/config/fonts"
    dest: "{{ lookup('env', 'HOME') }}/.fonts"
    state: link
    force: yes
