- name: Clone neovim repository
  git:
    force: yes
    repo: https://github.com/neovim/neovim
    dest: "{{ lookup('env', 'HOME') }}/bin/neovim"

- name: Make neovim
  become_user: root
  make:
    chdir: "{{ lookup('env', 'HOME') }}/bin/neovim"
    target: install

- name: Install AstroNvim
  git:
    force: yes
    repo: https://github.com/AstroNvim/AstroNvim 
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    depth: 1
