- name: Clone oh-my-zshrc
  shell: sh -c $(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --keep-zshrc --unattended

- name: Clone fzf-zsh-plugin
  git:
    force: yes
    repo: https://github.com/unixorn/fzf-zsh-plugin.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"
    depth: 1

- name: Clone spaceship-prompt
  git:
    force: yes
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    depth: 1

- name: Link spaceship theme to oh-my-zsh custom themes
  file:
    src: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
    force: yes
