- name: Setup zsh as main shell
  shell: chsh -s $(which zsh)

- name: Clean oh-my-zsh
  shell: rm -rf ~/.oh-my-zsh

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

- name: Clone fzf-zsh-plugin
  git:
    force: yes
    repo: https://github.com/unixorn/fzf-zsh-plugin.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/fzf-zsh-plugin"

- name: Clone zsh-suggestions
  git:
    force: yes
    repo: https://github.com/zsh-users/zsh-autosuggestions 
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Clone zsh-syntax-highlighting
  git:
    force: yes
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Install starship prompt
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
