- name: Install pacman packages
  tags: pacman
  become: yes
  become_user: root
  become_method: su
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - htop
    - python3
    - python-pip
    - python-wheel
    - python-virtualenv
    - docker-compose
    - docker
    - git
    - make
    - cmake
    - gcc
    - ripgrep
    - wget
    - terminator
    - firefox
    - telegram-desktop
    - bat
    - fzf
    - gnome-tweaks
    - alacritty
    - tmux
    - dconf-tools
    - xclip
    - pkg-config
    - npm
    - zsh
    - ranger
