- name: Install pacman packages
  tags: pacman
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - htop
    - python3
    - python-pip
    - python-wheel
    - python-virtualenv
    - docker-compose
    - docker
    - git
    - albert
    - plank
    - make
    - gcc
    - ripgrep
    - go
    - wget
    - terminator
    - firefox
    - telegram-desktop
    - bat
    - zathura
    - zathura-pdf-mupdf
    - texlive-most
    - ranger
