- name: Clone yay repository
  git:
    force: yes
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ lookup('env', 'HOME') }}/bin/yay"

- name: Make yay
  command: makepkg -si --noconfirm
  args:
    chdir: "{{ lookup('env', 'HOME') }}/bin/yay"

- name: Install yay packages
  command: yay -S --no-confirm {{ item }}
  loop:
    - autojump
    - spotify
