- block:
    - name: Purge nvim cache
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/{{ delete_file }}"
        state: absent
      loop:
        - .cache/nvim
        - .local/share/nvim
        - .config/nvim
      loop_control:
        loop_var: delete_file

    - name: Link nvim dotfiles/config dir in ~/.config
      ansible.builtin.file:
        src: "{{ lookup('env', 'HOME') }}/dotfiles/config/apps/nvim"
        dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
        state: link
        force: true
  tags: neovim
