[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[shell]
args = ["new-session", "-A", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"
