[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[[keyboard.bindings]]
chars = "\u001B[11~"
key = "F1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[12~"
key = "F2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13~"
key = "F3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[14~"
key = "F4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "Tab"
mods = "Control | Shift"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"
mods = "Control | Shift"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"
mods = "Control | Shift"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"
mods = "Control | Shift"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"
mods = "Control | Shift"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"
mods = "Control"

[shell]
args = ["new-session", "-A", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"
