- name: Install apt packages
  apt:
    name: "{{ package }}"
    state: present
  loop:
    - curl
    - htop
    - python3
    - python3-dev
    - python3-pip
    - python3-wheel
    - python3-venv
    - docker-compose
    - docker
    - git
    - albert
    - plank
    - make
    - cmake
    - gcc
    - g++
    - ripgrep
    - wget
    - terminator
    - firefox
    - batcat
    - gnome-tweak-tool
    - alacritty
    - tmux
    - dconf-editor
    - xclip
    - zsh
    - ranger
    - neovim
  loop_control:
    loop_var: package
  when: ansible_facts['os_family'] == 'Debian'
