- block:
    - name: Install starship prompt
      ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh -s -- -y

    - name: Link starship config
      ansible.builtin.file:
        src: "{{ lookup('env', 'HOME') }}/dotfiles/config/shell/starship/starship.toml"
        dest: "{{ lookup('env', 'HOME') }}/.config/starship.toml"
        state: link
        force: true
  tags: starship
