- block:
    - name: Swap CapsLock and ESC
      ansible.builtin.shell: sh -c "{{ lookup('env', 'HOME') }}/dotfiles/config/customization/keyboard/swapescape.sh"
      when: ansible_system == 'Linux'
  tags: keyboard
