- block:
    - name: Download WhiteSur-gtk-theme
      git:
        force: yes
        repo: https://github.com/vinceliuice/WhiteSur-gtk-theme
        dest: "{{ lookup('env', 'HOME') }}/bin/WhiteSur-gtk-theme"
        depth: 1

    - name: Install WhiteSur-gtk-theme
      become: true
      become_user: root
      shell: sh "{{ lookup('env', 'HOME') }}/bin/WhiteSur-gtk-theme/install.sh"

    # - name: Configure firefox based on WhiteSur-gtk-theme
    #   become: true
    #   become_user: root
    #   shell: sh "{{ lookup('env', 'HOME') }}/bin/WhiteSur-gtk-theme/tweaks.sh" -f monterey

    - name: Configure gdm based on WhiteSur-gtk-theme
      become: true
      become_user: root
      shell: sh "{{ lookup('env', 'HOME') }}/bin/WhiteSur-gtk-theme/tweaks.sh" -g -N -b "{{ lookup('env', 'HOME') }}/dotfiles/config/customization/wallpapers/wallpaper-default.jpg"
  when: ansible_system == 'Linux'
